# Generated by Django 4.0.3 on 2022-03-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUDENT_NO', models.CharField(max_length=255, unique=True)),
                ('Prefix', models.CharField(choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว')], max_length=255)),
                ('NAME', models.CharField(max_length=255)),
                ('LNAME', models.CharField(max_length=255)),
                ('train_year', models.CharField(max_length=255)),
                ('train_term', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=255)),
                ('Faculty_name', models.CharField(choices=[('วิศวกรรมศาสตร์', 'วิศวกรรมศาสตร์')], default='วิศวกรรมศาสตร์', max_length=255)),
                ('Filed_study', models.CharField(choices=[('คอมพิวเตอร์', 'คอมพิวเตอร์')], default='คอมพิวเตอร์', max_length=255)),
                ('train_room', models.CharField(choices=[('ECP1N', 'ECP1N'), ('ECP2N', 'ECP2N'), ('ECP3N', 'ECP3N'), ('ECP4N', 'ECP4N'), ('ECP2R', 'ECP2R'), ('ECP3R', 'ECP3R'), ('ECP4R', 'ECP4R'), ('ECP2Q', 'ECP2Q'), ('ECP3Q', 'ECP3Q'), ('ECP4Q', 'ECP4Q')], max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
