# Generated by Django 4.0.3 on 2022-03-29 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_coop11'),
    ]

    operations = [
        migrations.AddField(
            model_name='coop11',
            name='assessorname4',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
