# Generated by Django 4.0.3 on 2022-03-29 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_coop112_assessorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='coop112',
            name='verse16',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
