# Generated by Django 4.0.3 on 2022-03-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_coop21'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coop21',
        ),
    ]
