# Generated by Django 4.0.3 on 2022-03-30 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0004_alter_establishments_email_and_more'),
        ('assessments', '0009_coop21'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coop20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessorname1', models.CharField(max_length=255)),
                ('assessorname2', models.CharField(max_length=255)),
                ('student1', models.CharField(max_length=255)),
                ('student2', models.CharField(max_length=255)),
                ('student3', models.CharField(max_length=255)),
                ('verse1', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255)),
                ('verse2', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255)),
                ('verse3', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255)),
                ('verse4', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255)),
                ('verse5', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255)),
                ('verse6', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255)),
                ('versefull1', models.CharField(max_length=255)),
                ('establishments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishments.establishments')),
            ],
        ),
    ]
