# Generated by Django 4.0.3 on 2022-03-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_establishments_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishments',
            name='telephone',
            field=models.CharField(max_length=255),
        ),
    ]
